/:
  controller: main
  action: home




/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/recoverPassword:
  controller: user
  action: recoverPassword


/changePassword:
  controller: user
  action: changePassword

/dashboard:
  controller: admin
  action: home
  security: true

/users:
  controller: admin
  action: users
  security: true

/mail:
  controller: user
  action: sendRegisterMail

/verifyAccount:
  controller: user
  action: verifyAccount
