-
  controller: main
  action: home
  path: /


-
  path: /createCourse
  controller: course
  action: index
  method: GET
  param: []

-
  path: /createCourse
  controller: course
  action: create
  method: POST
  param: [ "name", "description", "cover", "category" ]

-
  controller: main
  action: contact
  path: /contact


-
  path: /front
  controller: main
  action: front
  method: GET

-
  controller: user
  action: login
  path: /login


-
  controller: user
  action: logout
  path: /logout


-
  controller: user
  action: register
  method: GET
  path: /register
  param: []

-
  controller: user
  action: register
  method: POST
  path: /register
  param: [ ]


-
  controller: admin
  action: home
  security: true
  path: /dashboard

